name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Configure Git to Merge
        run: git config pull.rebase false
      - name: Pull from hub to avoid conflicts
        run: git pull https://rahulRhodes:$HF_TOKEN@huggingface.co/spaces/rahulRhodes/Search_Engine_Model main
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://rahulRhodes:$HF_TOKEN@huggingface.co/spaces/rahulRhodes/Search_Engine_Model main
