name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set Git Identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Configure Git to Merge
        run: git config pull.rebase false

      - name: Pull and resolve README.md conflict (keep local)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git pull --allow-unrelated-histories https://rahulRhodes:$HF_TOKEN@huggingface.co/spaces/rahulRhodes/Search_Engine_Model main || true
          git checkout --ours README.md || true
          git add README.md || true
          git commit -m "Auto-resolve README.md conflict by keeping local version" || true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://rahulRhodes:$HF_TOKEN@huggingface.co/spaces/rahulRhodes/Search_Engine_Model main
