name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set Git Identity
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Configure Git to Merge
        run: git config pull.rebase false

      - name: Pull from Hugging Face (allow unrelated histories)
        run: git pull --allow-unrelated-histories https://rahulRhodes:$HF_TOKEN@huggingface.co/spaces/rahulRhodes/Search_Engine_Model main

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://rahulRhodes:$HF_TOKEN@huggingface.co/spaces/rahulRhodes/Search_Engine_Model main
